'use client';
import {useEffect,useState,useRef} from 'react';
import {categories,defaults,Work,Asset} from '../lib/catalog';
function Media({asset}:{asset:Asset}){const src='/api/media/'+asset.id;if(asset.mime.startsWith('image/'))return <img src={src} alt={asset.name} loading="lazy"/>;if(asset.mime.startsWith('video/'))return <video controls preload="metadata" playsInline src={src}/>;return <a className="file-link" href={src} target="_blank" rel="noopener noreferrer">{asset.mime==='application/pdf'?'阅读 PDF':'查看文本'} · {asset.name}</a>;}
export default function Portfolio(){const [profile,setProfile]=useState(defaults),[works,setWorks]=useState<Work[]>([]),[category,setCategory]=useState('all'),[menu,setMenu]=useState(false),[selected,setSelected]=useState<Work|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');const menuDialog=useRef<HTMLDialogElement>(null),detail=useRef<HTMLDialogElement>(null),track=useRef<HTMLDivElement>(null);
async function load(){setError('');setLoading(true);try{const responses=await Promise.all([fetch('/api/works'),fetch('/api/settings')]);if(responses.some(r=>!r.ok))throw Error('暂时无法读取作品，请稍后重试。');const [w,p]=await Promise.all(responses.map(r=>r.json()));setWorks(w as Work[]);setProfile(p as typeof defaults);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
useEffect(()=>{load();},[]);useEffect(()=>{if(menu)menuDialog.current?.showModal();else menuDialog.current?.close();},[menu]);useEffect(()=>{if(selected)detail.current?.showModal();else detail.current?.close();},[selected]);
const choose=(id:string)=>{setCategory(id);setMenu(false);setTimeout(()=>document.getElementById('archive')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'}),40);};
useEffect(()=>{const c=(document as any).modelContext;if(!c?.registerTool)return;const a=new AbortController();Promise.resolve(c.registerTool({name:'browse_portfolio_category',description:'Select a portfolio category and display its works.',inputSchema:{type:'object',properties:{category:{type:'string',enum:['all',...categories.map(x=>x.id)]}},required:['category'],additionalProperties:false},annotations:{readOnlyHint:true},execute:async({category:id}:{category:string})=>{if(id!=='all'&&!categories.some(c=>c.id===id))throw Error('Unknown category');choose(id);return {category:id};}},{signal:a.signal})).catch(()=>{});return()=>a.abort();},[]);
const current=categories.find(c=>c.id===category),visible=category==='all'?works:works.filter(w=>w.category===category);
return <><a className="skip" href="#archive">跳到作品</a><header className="header"><a className="brand" href="/">{profile.name}<span>{profile.english}</span></a><nav><a href="#about">关于</a><button className="menu-toggle" onClick={()=>setMenu(true)} aria-haspopup="dialog">作品目录 <span className="plus">＋</span></button></nav></header>
<main><section className="hero"><div className="hero-index">INDEPENDENT CREATIVE ARCHIVE <span>01 — 07</span></div><div className="hero-type"><p className="eyebrow">观察 · 表达 · 实验</p><h1>创作，<br/><span>不止一面。</span></h1><p className="intro">{profile.intro}</p><button className="primary" onClick={()=>setMenu(true)}>打开作品目录 <span>＋</span></button></div><img className="hero-art" src="/botanical-hero.png" alt="白底细线植物插画"/><span className="side-note">A COLLECTION OF IDEAS & OBSERVATIONS</span><div className="hero-bottom"><span>不断探索，持续生长。</span><a href="#archive">向下浏览 · SCROLL</a><span>PORTFOLIO / 2026</span></div></section>
<section className="archive" id="archive"><div className="section-top"><p className="eyebrow">01 / SELECTED WORKS</p><span>{String(visible.length).padStart(2,'0')} 件作品</span></div><div className="archive-heading"><h2>{current?.name||'作品档案'}<em>{current?.en||'The collection'}</em></h2><button className="filter-button" onClick={()=>setMenu(true)}>{current?'切换板块':'选择板块'} <span>＋</span></button></div><p className="archive-note">{current?.note||'不同的媒介，同样的好奇心。'}</p>
{loading?<div className="empty"><span className="serif-symbol">…</span><p>正在展开作品档案</p></div>:error?<div className="empty" role="alert"><p>{error}</p><button onClick={load}>重新加载</button></div>:visible.length===0?<div className="empty"><span className="empty-no">{current?String(categories.indexOf(current)+1).padStart(2,'0'):'00'}</span><div><p className="eyebrow">ROOM FOR WHAT COMES NEXT</p><h3>{current?`${current.name}作品，待续。`:'下一件作品，从这里开始。'}</h3><p>作品正在整理中，期待与你分享。</p></div></div>:<><div className="work-track" ref={track} aria-label="作品横向画廊" tabIndex={0}>{visible.map((w,i)=>{const cover=w.assets.find(a=>a.mime.startsWith('image/'));return <button className={'work-card card-'+w.category} key={w.id} onClick={()=>setSelected(w)}><div className="work-cover">{cover?<img alt={w.title} src={'/api/media/'+cover.id} loading="lazy"/>:w.assets.some(a=>a.mime.startsWith('video/'))?<video src={'/api/media/'+w.assets.find(a=>a.mime.startsWith('video/'))!.id} muted preload="metadata"/>:<div className="type-cover"><span>{categories.find(c=>c.id===w.category)?.en}</span><strong>{w.title}</strong><small>{w.description.slice(0,90)}</small></div>}<span className="work-number">{String(i+1).padStart(2,'0')}</span></div><div className="card-meta"><h3>{w.title}</h3><span>{w.year}</span></div><p>{categories.find(c=>c.id===w.category)?.name} {w.description&&' / '+w.description}</p></button>;})}</div><div className="track-controls"><span>左右滑动，慢慢看。</span><div><button onClick={()=>track.current?.scrollBy({left:-track.current.clientWidth*.85,behavior:'smooth'})}>上一组</button><button onClick={()=>track.current?.scrollBy({left:track.current.clientWidth*.85,behavior:'smooth'})}>下一组</button></div></div></>}
</section><section id="about" className="about"><p className="eyebrow">02 / A LITTLE ABOUT ME</p><div><h2>始终好奇，<br/><em>保持感受。</em></h2><p>{profile.about}</p>{profile.email&&<a href={'mailto:'+profile.email}>{profile.email}</a>}</div><span className="about-stamp">{profile.english}<br/>CREATIVE<br/>ARCHIVE</span></section></main>
<footer><span>© {new Date().getFullYear()} {profile.name} / {profile.english}</span><span>每一份创作，都有自己的节奏。</span><a href="/admin">管理作品</a></footer>
<dialog ref={menuDialog} className="category-dialog" onCancel={()=>setMenu(false)} onClick={e=>{if(e.target===menuDialog.current)setMenu(false);}}><div className="dialog-top"><span className="eyebrow">INDEX / 作品目录</span><button onClick={()=>setMenu(false)} aria-label="关闭目录">关闭 ×</button></div><h2>想先看哪一面？</h2><button className="all-category" onClick={()=>choose('all')}>全部作品 <span>ALL WORKS</span></button><div className="category-list">{categories.map((c,i)=><button key={c.id} onClick={()=>choose(c.id)}><span className="category-no">0{i+1}</span><span className="category-name">{c.name}<small>{c.en}</small></span><span className="category-count">{String(works.filter(w=>w.category===c.id).length).padStart(2,'0')}</span></button>)}</div></dialog>
<dialog ref={detail} className="detail-dialog" onCancel={()=>setSelected(null)}>{selected&&<><div className="dialog-top"><span>{categories.find(c=>c.id===selected.category)?.name} / {selected.year}</span><button onClick={()=>setSelected(null)} aria-label="关闭作品">关闭 ×</button></div><h2>{selected.title}</h2><p className="detail-description">{selected.description}</p>{selected.url&&<a className="primary external" href={selected.url} target="_blank" rel="noopener noreferrer">{selected.category==='vibecoding'?'访问项目':'打开作品链接'}</a>}<div className={'detail-assets '+(selected.category==='photography'?'photo-assets':'')}>{selected.assets.map(a=><Media key={a.id} asset={a}/>)}</div>{selected.body&&<div className="prose">{selected.body}</div>}<button className="back-button" onClick={()=>setSelected(null)}>返回作品</button></>}</dialog></>;}
